# Generated by Django 5.2.4 on 2025-07-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.IntegerField(
                help_text="Укажите Ваш ID telegram",
                max_length=9,
                unique=True,
                verbose_name="Телеграм ID",
            ),
        ),
    ]
