# Generated by Django 5.2.4 on 2025-07-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_telegram_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telegram_id",
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите Ваш ID telegram",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Телеграм ID",
            ),
        ),
    ]
