# Generated by Django 5.2.4 on 2025-07-09 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Место, в котором необходимо выполнять привычку",
                        max_length=30,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Время, когда необходимо выполнять привычку",
                        null=True,
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Действие, которое представляет собой привычка",
                        max_length=50,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_enjoyable",
                    models.BooleanField(
                        blank=True,
                        help_text="Привычка, способ вознаградить себя за выполнение полезной привычки",
                        null=True,
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("Еженедельно", "Еженедельно"),
                            ("Ежедневно", "Ежедневно"),
                            ("Каждые 2 дня", "Каждые 2 дня"),
                            ("Каждые 3 дня", "Каждые 3 дня"),
                            ("Каждые 4 дня", "Каждые 4 дня"),
                            ("По понедельникам", "По понедельникам"),
                            ("По вторникам", "По вторникам"),
                            ("По средам", "По четвергам"),
                            ("По четвергам", "По четвергам"),
                            ("По пятницам", "По пятницам"),
                            ("По субботам", "По субботам"),
                            ("По воскресеньям", "По воскресеньям"),
                            ("2 раза в день", "2 раза в день"),
                            ("3 раза в день", "3 раза в день"),
                        ],
                        default="Ежедневно",
                        help_text="Периодичность выполнения привычки для напоминания в днях",
                        max_length=16,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Вознаграждение за выполнение привычки",
                        max_length=50,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Время, которое предположительно нужно потратить на выполнение привычки",
                        null=True,
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Привычки можно публиковать в общий доступ, чтобы другие пользователи могли брать в пример Ваши привычки",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Привычка, которая связана с другой привычкой, важно указывать для полезных привычек, но не для приятных",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
