# Generated by Django 5.2.4 on 2025-07-09 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Признак активности"),
        ),
        migrations.AddField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_enjoyable",
            field=models.BooleanField(
                blank=True,
                help_text="Привычка, способ вознаградить себя за выполнение полезной привычки",
                null=True,
                verbose_name="Признак приятной привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Время, которое предположительно нужно потратить на выполнение привычки. Укажите в минутах",
                null=True,
                verbose_name="Время на выполнение",
            ),
        ),
    ]
