# Generated by Django 5.2.4 on 2025-07-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "habits",
            "0002_habit_is_active_habit_owner_alter_habit_is_enjoyable_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="deadline",
        ),
        migrations.AddField(
            model_name="habit",
            name="date_deadline",
            field=models.DateField(
                blank=True,
                help_text="Дата, когда необходимо выполнять привычку",
                null=True,
                verbose_name="Дата выполнения привычки",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="time_deadline",
            field=models.TimeField(
                blank=True,
                help_text="Время, когда необходимо выполнять привычку",
                null=True,
                verbose_name="Время выполнения привычки",
            ),
        ),
    ]
